controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_controller:
      type: position_controllers/JointGroupPositionController

    rear_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController


steering_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint

rear_wheel_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
